version: '3.7'

services:
  server:
    env_file:
      - ./meal-dash-business/.env.development.local
    container_name: server
    depends_on:
      - mysql-master
    build: ./meal-dash-business
    ports:
      - '3000:3000'
  mysql-master:
    container_name: mysql-master
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root  
    volumes:
      - ./mysql-master:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

