version: '4.0'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    environment:
      - PORT = 3000
      - DB_HOST = mysql-master
      - DB_PORT = 3306
      - DB_USER = root
      - DB_PASSWORD = root
      - DB_DATABASE = meal-dash
      - SECRET_KEY = best_key_in_the_whole_world
      - LOG_FORMAT = dev
      - LOG_DIR = ../../../logs
      - ORIGIN = *
      - CREDENTIALS = true
      - SMTP_HOST = smtp.gmail.com
      - SMTP_PORT = 587
      - SMTP_USERNAME = meal.dash.capstone@gmail.com
      - SMTP_PASSWORD = "ccxbgveusqkcijmr"
    restart: 'unless-stopped'
    links:
      - mysql-master
    depends_on:
      - mysql-master
  mysql-master:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root  
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

