version: '4.0'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    restart: 'unless-stopped'
    links:
      - mysql-master
    depends_on:
      - mysql-master
  mysql-master:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root  
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

