tags:
- name: Subscription
  description: Subscription API

paths:
  # [POST] subscription
  /subscription:
    post:
      tags:
      - Subscription
      summary: Add subscription plan
      parameters:
      - name: body
        in: body
        description: subscription plan Data
        required: true
        schema:
          $ref: '#/definitions/subscription'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# definitions
definitions:
  subscription:
    type: object
    required:
        - ends_at
        - starts_at
        - created_at
        - deleted_at
        - is_deleted
        - mealplan_id
    properties:
      ends_at:
        type: string
        format: date-time
        description: subscription end date
      starts_at:
        type: string
        format: date-time
        description: subscription start date
      created_at:
        type: string
        format: date-time
        description: subscription created date
      deleted_at:
        type: string
        format: date-time
        description: subscription deleted date
      is_deleted:
        type: boolean
        description: subscription is deleted
      mealplan_id:
        type: number
        description: subscription meal plan id
schemes:
 - https
 - http