name: 'Assert Branch Naming Convention'
on: pull_request

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          # regex: '([a-z])+\/([a-z])+' # Regex the branch should match. This example enforces grouping
          allowed_prefixes: 'feature/,release/flutter-app-,release/node-server-,release/rest-docs-,hotfix/' # All branches should start with the given prefix
          ignore: main,production # Ignore exactly matching branch names from convention
          min_length: 5 # Min length of the branch name
          max_length: 40 # Max length of the branch name
