#The workflow is triggered on pull request to the production branch when head_ref starts with release/flutter-app-. In the workflow the job 'code-analysis' analyses and checks formatting of the code in lib and test folders.

name: Flutter CI

on:
  pull_request:
    branches: [ "production" ]

jobs:
  code-analysis:
    if: startsWith(github.head_ref, 'release/flutter-app-')
    
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mealdash_flutter_app

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Flutter analyze 
        run: flutter analyze --no-pub --no-current-package --fatal-infos --fatal-warnings lib test
      - name: Flutter format
        run: flutter format --set-exit-if-changed lib test
#     - name: Install dependencies
#       run: flutter pub get
#     # - name: Format code
#     #   run: flutter format --set-exit-if-changed .
#     - name: Build APK
#       run: flutter build apk --release
#     - name: Upload APK
#       uses: actions/upload-artifact@v2
#       with:
#         name: app-release.apk
#         path: ./flutter-app/build/app/outputs/flutter-apk/app-release.apk
      
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Download APK
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: app-release.APK
  #   - name: Play Store Deploy
  #     uses: r0adkll/upload-google-play@v2
  #     with:
  #       # The package name of the application
  #       packageName: com.example.mealdash_flutter_app
  #       # The service account JSON
  #       serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
  #       # The path to the APK to upload
  #       releaseFile: app-release.apk
  #       # The track to deploy to
  #       track: internal
  #       # The user fraction to use when rolling out the release
  #       userFraction: 0.1

  


