# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: [ "release/flutter-app-*" ]
  pull_request:
    branches: [ "production" ]

jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mealdash_flutter_app
    steps:
    - name: Install Flutter
      # You may pin to the exact commit or the version.
      # uses: britannio/action-install-flutter@a486b7e3148e54a76390d849100b9dee819ff810
      uses: britannio/action-install-flutter@v1.1
      #with:
        # The channel/version of Flutter to be used e.g., beta or 2.0.0
        #version: # optional, default is stable
    
    # Get flutter dependencies.
    - run: flutter pub get
    
    # Check for any formatting issues in the code.
    #- run: flutter format --set-exit-if-changed .
    
    # Statically analyze the Dart code for any errors.
    - run: flutter analyze .
    
    # Run widget tests for our flutter project.
    #- run: flutter test
    
    # Build apk.
    #- run: flutter build apk
    
    # Upload generated apk to the artifacts.
    #- uses: actions/upload-artifact@v1
    #  with:
    #    name: release-apk
    #    path: build/app/outputs/apk/release/app-release.apk
