#The workflow is triggered on pull request to the production branch. The build job builds the docker image and pushes it to Docker Hub. The deploy job pulls the image from Docker Hub and deploys it to the production server.

name: Node.js

on:
  pull_request:
    branches: [ "production" ]

jobs:
  build:
    if: startsWith(github.ref, 'refs/heads/release/node-server-')

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: meal-dash-business

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . -t mealdash-node-server
      # - name: Log in to Docker Hub
      #   run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      # - name: Push the Docker image to Docker Hub
      #   run: docker push mealdash-node-server

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Pull the Docker image from Docker Hub
  #       run: docker pull mealdash-node-server
  #     - name: Deploy the Docker image to the production server
  #       run: ssh -i ${{ secrets.SSH_KEY }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker pull mealdash-node-server && docker stop mealdash-node-server && docker rm mealdash-node-server && docker run -d --name mealdash-node-server -p 3000:3000 mealdash-node-server" 
      
